// Türkiye şehir ve ilçe verileri
export const TURKEY_CITIES = [
  'Adana', 'Adıyaman', 'Afyonkarahisar', 'Ağrı', 'Aksaray', 'Amasya', 'Ankara', 'Antalya',
  'Ardahan', 'Artvin', 'Aydın', 'Balıkesir', 'Bartın', 'Batman', 'Bayburt', 'Bilecik',
  'Bingöl', 'Bitlis', 'Bolu', 'Burdur', 'Bursa', 'Çanakkale', 'Çankırı', 'Çorum',
  'Denizli', 'Diyarbakır', 'Düzce', 'Edirne', 'Elazığ', 'Erzincan', 'Erzurum', 'Eskişehir',
  'Gaziantep', 'Giresun', 'Gümüşhane', 'Hakkari', 'Hatay', 'Iğdır', 'Isparta', 'İstanbul',
  'İzmir', 'Kahramanmaraş', 'Karabük', 'Karaman', 'Kars', 'Kastamonu', 'Kayseri', 'Kırıkkale',
  'Kırklareli', 'Kırşehir', 'Kilis', 'Kocaeli', 'Konya', 'Kütahya', 'Malatya', 'Manisa',
  'Mardin', 'Mersin', 'Muğla', 'Muş', 'Nevşehir', 'Niğde', 'Ordu', 'Osmaniye', 'Rize',
  'Sakarya', 'Samsun', 'Siirt', 'Sinop', 'Sivas', 'Şanlıurfa', 'Şırnak', 'Tekirdağ',
  'Tokat', 'Trabzon', 'Tunceli', 'Uşak', 'Van', 'Yalova', 'Yozgat', 'Zonguldak'
];

export const TURKEY_DISTRICTS: Record<string, string[]> = {
  'Adana': ['Seyhan', 'Çukurova', 'Yüreğir', 'Sarıçam', 'Karaisalı', 'Ceyhan', 'Kozan', 'İmamoğlu', 'Pozantı', 'Aladağ', 'Feke', 'Saimbeyli', 'Tufanbeyli', 'Yumurtalık'],
  'Adıyaman': ['Merkez', 'Kahta', 'Besni', 'Gölbaşı', 'Gerger', 'Çelikhan', 'Samsat', 'Sincik', 'Tut'],
  'Afyonkarahisar': ['Merkez', 'Sandıklı', 'Dinar', 'Bolvadin', 'Emirdağ', 'Çay', 'Sultandağı', 'İhsaniye', 'Sinanpaşa', 'Şuhut', 'Dazkırı', 'Başmakçı', 'Bayat', 'Çobanlar', 'Evciler', 'Hocalar', 'İscehisar', 'Kızılören'],
  'Ağrı': ['Merkez', 'Patnos', 'Doğubayazıt', 'Diyadin', 'Eleşkirt', 'Tutak', 'Taşlıçay', 'Hamur'],
  'Aksaray': ['Merkez', 'Ortaköy', 'Eskil', 'Ağaçören', 'Sarıyahşi', 'Güzelyurt', 'Gülağaç', 'Sultanhanı'],
  'Amasya': ['Merkez', 'Merzifon', 'Suluova', 'Gümüşhacıköy', 'Taşova', 'Göynücek', 'Hamamözü'],
  'Ankara': ['Çankaya', 'Keçiören', 'Mamak', 'Etimesgut', 'Sincan', 'Yenimahalle', 'Altındağ', 'Pursaklar', 'Gölbaşı', 'Polatlı', 'Beypazarı', 'Çubuk', 'Kahramankazan', 'Haymana', 'Kızılcahamam', 'Şereflikoçhisar', 'Nallıhan', 'Ayaş', 'Bala', 'Güdül', 'Kalecik', 'Çamlıdere', 'Elmadağ', 'Evren', 'Akyurt'],
  'Antalya': ['Muratpaşa', 'Kepez', 'Konyaaltı', 'Aksu', 'Döşemealtı', 'Alanya', 'Manavgat', 'Serik', 'Kaş', 'Kemer', 'Kumluca', 'Finike', 'Demre', 'Gazipaşa', 'Gündoğmuş', 'İbradı', 'Akseki', 'Elmalı', 'Korkuteli'],
  'Ardahan': ['Merkez', 'Göle', 'Çıldır', 'Posof', 'Hanak', 'Damal'],
  'Artvin': ['Merkez', 'Hopa', 'Arhavi', 'Borçka', 'Şavşat', 'Yusufeli', 'Ardanuç', 'Murgul'],
  'Aydın': ['Efeler', 'Nazilli', 'Söke', 'Kuşadası', 'Didim', 'Çine', 'Germencik', 'İncirliova', 'Köşk', 'Sultanhisar', 'Bozdoğan', 'Karacasu', 'Kuyucak', 'Yenipazar', 'Buharkent', 'Karpuzlu', 'Koçarlı'],
  'Balıkesir': ['Altıeylül', 'Karesi', 'Bandırma', 'Edremit', 'Gönen', 'Burhaniye', 'Ayvalık', 'Bigadiç', 'Susurluk', 'Erdek', 'Havran', 'Dursunbey', 'Sındırgı', 'İvrindi', 'Savaştepe', 'Kepsut', 'Manyas', 'Marmara', 'Balya'],
  'Bartın': ['Merkez', 'Ulus', 'Kurucaşile', 'Amasra'],
  'Batman': ['Merkez', 'Kozluk', 'Sason', 'Beşiri', 'Gercüş', 'Hasankeyf'],
  'Bayburt': ['Merkez', 'Demirözü', 'Aydıntepe'],
  'Bilecik': ['Merkez', 'Bozüyük', 'Osmaneli', 'Söğüt', 'Gölpazarı', 'Pazaryeri', 'İnhisar', 'Yenipazar'],
  'Bingöl': ['Merkez', 'Genç', 'Solhan', 'Karlıova', 'Kiğı', 'Adaklı', 'Yayladere', 'Yedisu'],
  'Bitlis': ['Merkez', 'Tatvan', 'Ahlat', 'Adilcevaz', 'Güroymak', 'Hizan', 'Mutki'],
  'Bolu': ['Merkez', 'Gerede', 'Mudurnu', 'Mengen', 'Göynük', 'Seben', 'Dörtdivan', 'Kıbrıscık', 'Yeniçağa'],
  'Burdur': ['Merkez', 'Bucak', 'Gölhisar', 'Yeşilova', 'Tefenni', 'Ağlasun', 'Çavdır', 'Çeltikçi', 'Karamanlı', 'Kemer', 'Altınyayla'],
  'Bursa': ['Osmangazi', 'Nilüfer', 'Yıldırım', 'Görükle', 'İnegöl', 'Mustafakemalpaşa', 'Gemlik', 'Mudanya', 'Kestel', 'Gürsu', 'Karacabey', 'Orhangazi', 'İznik', 'Yenişehir', 'Keles', 'Orhaneli', 'Büyükorhan', 'Harmancık'],
  'Çanakkale': ['Merkez', 'Biga', 'Çan', 'Gelibolu', 'Ayvacık', 'Ezine', 'Lapseki', 'Yenice', 'Bayramiç', 'Gökçeada', 'Bozcaada', 'Eceabat'],
  'Çankırı': ['Merkez', 'Çerkeş', 'Şabanözü', 'Ilgaz', 'Kurşunlu', 'Orta', 'Kızılırmak', 'Bayramören', 'Eldivan', 'Korgun', 'Yapraklı', 'Atkaracalar'],
  'Çorum': ['Merkez', 'Sungurlu', 'Osmancık', 'Alaca', 'İskilip', 'Kargı', 'Mecitözü', 'Bayat', 'Ortaköy', 'Dodurga', 'Uğurludağ', 'Oğuzlar', 'Laçin', 'Boğazkale'],
  'Denizli': ['Merkezefendi', 'Pamukkale', 'Çivril', 'Acıpayam', 'Tavas', 'Sarayköy', 'Buldan', 'Çal', 'Honaz', 'Kale', 'Serinhisar', 'Güney', 'Çameli', 'Çardak', 'Baklan', 'Bozkurt', 'Beyağaç', 'Babadağ'],
  'Diyarbakır': ['Kayapınar', 'Bağlar', 'Yenişehir', 'Sur', 'Bismil', 'Ergani', 'Silvan', 'Çermik', 'Çüngüş', 'Dicle', 'Eğil', 'Hani', 'Hazro', 'Kocaköy', 'Kulp', 'Lice'],
  'Düzce': ['Merkez', 'Akçakoca', 'Gölyaka', 'Cumayeri', 'Çilimli', 'Gümüşova', 'Kaynaşlı', 'Yığılca'],
  'Edirne': ['Merkez', 'Keşan', 'Uzunköprü', 'Havsa', 'Enez', 'İpsala', 'Süloğlu', 'Lalapaşa', 'Meriç'],
  'Elazığ': ['Merkez', 'Kovancılar', 'Karakoçan', 'Palu', 'Maden', 'Sivrice', 'Keban', 'Baskil', 'Arıcak', 'Alacakaya', 'Ağın'],
  'Erzincan': ['Merkez', 'Tercan', 'Üzümlü', 'Refahiye', 'Çayırlı', 'İliç', 'Kemaliye', 'Kemah', 'Otlukbeli'],
  'Erzurum': ['Yakutiye', 'Palandöken', 'Aziziye', 'Oltu', 'Horasan', 'Pasinler', 'Aşkale', 'Hınıs', 'Tekman', 'Karaçoban', 'Karayazı', 'Köprüköy', 'Narman', 'Olur', 'Pazaryolu', 'İspir', 'Tortum', 'Uzundere', 'Şenkaya', 'Çat'],
  'Eskişehir': ['Odunpazarı', 'Tepebaşı', 'Sivrihisar', 'Çifteler', 'Mahmudiye', 'Seyitgazi', 'Sarıcakaya', 'Alpu', 'Beylikova', 'İnönü', 'Mihalıççık', 'Han', 'Günyüzü', 'Mihalgazi'],
  'Gaziantep': ['Şahinbey', 'Şehitkamil', 'Nizip', 'İslahiye', 'Nurdağı', 'Oğuzeli', 'Araban', 'Yavuzeli', 'Karkamış'],
  'Giresun': ['Merkez', 'Bulancak', 'Espiye', 'Görele', 'Tirebolu', 'Keşap', 'Piraziz', 'Eynesil', 'Dereli', 'Yağlıdere', 'Şebinkarahisar', 'Alucra', 'Çamoluk', 'Güce', 'Doğankent', 'Çanakçı'],
  'Gümüşhane': ['Merkez', 'Kelkit', 'Şiran', 'Torul', 'Kürtün', 'Köse'],
  'Hakkari': ['Merkez', 'Yüksekova', 'Şemdinli', 'Çukurca', 'Derecik'],
  'Hatay': ['Antakya', 'İskenderun', 'Defne', 'Arsuz', 'Payas', 'Dörtyol', 'Samandağ', 'Kırıkhan', 'Reyhanlı', 'Altınözü', 'Kumlu', 'Hassa', 'Belen', 'Erzin', 'Yayladağı'],
  'Iğdır': ['Merkez', 'Tuzluca', 'Aralık', 'Karakoyunlu'],
  'Isparta': ['Merkez', 'Yalvaç', 'Eğirdir', 'Şarkikaraağaç', 'Gelendost', 'Keçiborlu', 'Senirkent', 'Uluborlu', 'Atabey', 'Gönen', 'Sütçüler', 'Aksu', 'Yenişarbademli'],
  'İstanbul': ['Kadıköy', 'Beşiktaş', 'Şişli', 'Bakırköy', 'Fatih', 'Üsküdar', 'Beyoğlu', 'Maltepe', 'Ataşehir', 'Kartal', 'Pendik', 'Tuzla', 'Sarıyer', 'Beykoz', 'Ümraniye', 'Sultanbeyli', 'Sancaktepe', 'Çekmeköy', 'Şile', 'Adalar', 'Başakşehir', 'Bahçelievler', 'Bağcılar', 'Güngören', 'Esenler', 'Bayrampaşa', 'Eyüpsultan', 'Gaziosmanpaşa', 'Kağıthane', 'Sultangazi', 'Arnavutköy', 'Esenyurt', 'Küçükçekmece', 'Avcılar', 'Beylikdüzü', 'Büyükçekmece', 'Çatalca', 'Silivri', 'Zeytinburnu'],
  'İzmir': ['Konak', 'Karşıyaka', 'Bornova', 'Buca', 'Bayraklı', 'Çiğli', 'Gaziemir', 'Karabağlar', 'Balçova', 'Narlıdere', 'Güzelbahçe', 'Torbalı', 'Menemen', 'Bergama', 'Aliağa', 'Ödemiş', 'Tire', 'Kemalpaşa', 'Foça', 'Seferihisar', 'Urla', 'Çeşme', 'Selçuk', 'Dikili', 'Kiraz', 'Beydağ', 'Bayındır', 'Menderes', 'Karaburun', 'Kınık'],
  'Kahramanmaraş': ['Dulkadiroğlu', 'Onikişubat', 'Elbistan', 'Afşin', 'Türkoğlu', 'Pazarcık', 'Göksun', 'Andırın', 'Çağlayancerit', 'Nurhak', 'Ekinözü'],
  'Karabük': ['Merkez', 'Safranbolu', 'Eskipazar', 'Yenice', 'Eflani', 'Ovacık'],
  'Karaman': ['Merkez', 'Ermenek', 'Sarıveliler', 'Kazımkarabekir', 'Ayrancı', 'Başyayla'],
  'Kars': ['Merkez', 'Sarıkamış', 'Kağızman', 'Selim', 'Digor', 'Susuz', 'Arpaçay', 'Akyaka'],
  'Kastamonu': ['Merkez', 'Tosya', 'Taşköprü', 'İnebolu', 'Araç', 'Cide', 'Çatalzeytin', 'Abana', 'Bozkurt', 'Daday', 'Devrekani', 'Küre', 'Seydiler', 'Şenpazar', 'Ağlı', 'Azdavay', 'Doğanyurt', 'Hanönü', 'İhsangazi', 'Pınarbaşı'],
  'Kayseri': ['Melikgazi', 'Kocasinan', 'Talas', 'Hacılar', 'İncesu', 'Develi', 'Yahyalı', 'Bünyan', 'Pınarbaşı', 'Tomarza', 'Sarıoğlan', 'Yeşilhisar', 'Felahiye', 'Sarız', 'Akkışla', 'Özvatan'],
  'Kırıkkale': ['Merkez', 'Yahşihan', 'Delice', 'Keskin', 'Sulakyurt', 'Balışeyh', 'Çelebi', 'Karakeçili', 'Bahşılı'],
  'Kırklareli': ['Merkez', 'Lüleburgaz', 'Babaeski', 'Vize', 'Pınarhisar', 'Demirköy', 'Kofçaz', 'Pehlivanköy'],
  'Kırşehir': ['Merkez', 'Kaman', 'Mucur', 'Çiçekdağı', 'Akpınar', 'Boztepe', 'Akçakent'],
  'Kilis': ['Merkez', 'Musabeyli', 'Elbeyli', 'Polateli'],
  'Kocaeli': ['İzmit', 'Gebze', 'Darıca', 'Derince', 'Körfez', 'Gölcük', 'Çayırova', 'Başiskele', 'Kartepe', 'Dilovası', 'Kandıra', 'Karamürsel'],
  'Konya': ['Selçuklu', 'Meram', 'Karatay', 'Ereğli', 'Akşehir', 'Beyşehir', 'Seydişehir', 'Cihanbeyli', 'Çumra', 'Karapınar', 'Kulu', 'Bozkır', 'Hadim', 'Ilgın', 'Kadınhanı', 'Sarayönü', 'Yunak', 'Hüyük', 'Altınekin', 'Çeltik', 'Derbent', 'Derebucak', 'Doğanhisar', 'Emirgazi', 'Güneysinir', 'Halkapınar', 'Taşkent', 'Tuzlukçu', 'Ahırlı', 'Yalıhüyük'],
  'Kütahya': ['Merkez', 'Tavşanlı', 'Simav', 'Gediz', 'Emet', 'Altıntaş', 'Domaniç', 'Aslanapa', 'Çavdarhisar', 'Dumlupınar', 'Hisarcık', 'Pazarlar', 'Şaphane'],
  'Malatya': ['Battalgazi', 'Yeşilyurt', 'Darende', 'Akçadağ', 'Doğanşehir', 'Hekimhan', 'Arguvan', 'Pütürge', 'Arapgir', 'Yazıhan', 'Kale', 'Kuluncak', 'Doğanyol'],
  'Manisa': ['Şehzadeler', 'Yunusemre', 'Turgutlu', 'Akhisar', 'Salihli', 'Soma', 'Alaşehir', 'Saruhanlı', 'Kula', 'Demirci', 'Gördes', 'Kırkağaç', 'Sarıgöl', 'Selendi', 'Ahmetli', 'Gölmarmara', 'Köprübaşı'],
  'Mardin': ['Artuklu', 'Kızıltepe', 'Nusaybin', 'Midyat', 'Derik', 'Mazıdağı', 'Savur', 'Dargeçit', 'Ömerli', 'Yeşilli'],
  'Mersin': ['Akdeniz', 'Mezitli', 'Toroslar', 'Yenişehir', 'Tarsus', 'Erdemli', 'Silifke', 'Anamur', 'Aydıncık', 'Bozyazı', 'Çamlıyayla', 'Gülnar', 'Mut'],
  'Muğla': ['Menteşe', 'Bodrum', 'Fethiye', 'Marmaris', 'Milas', 'Ortaca', 'Dalaman', 'Datça', 'Köyceğiz', 'Ula', 'Yatağan', 'Kavaklıdere', 'Seydikemer'],
  'Muş': ['Merkez', 'Malazgirt', 'Bulanık', 'Varto', 'Hasköy', 'Korkut'],
  'Nevşehir': ['Merkez', 'Ürgüp', 'Avanos', 'Derinkuyu', 'Gülşehir', 'Hacıbektaş', 'Kozaklı', 'Acıgöl'],
  'Niğde': ['Merkez', 'Bor', 'Çamardı', 'Ulukışla', 'Çiftlik', 'Altunhisar'],
  'Ordu': ['Altınordu', 'Ünye', 'Fatsa', 'Perşembe', 'Korgan', 'Kumru', 'Ulubey', 'Gölköy', 'Mesudiye', 'Aybastı', 'Akkuş', 'Çamaş', 'Çatalpınar', 'Çaybaşı', 'Gülyalı', 'Gürgentepe', 'İkizce', 'Kabadüz', 'Kabataş'],
  'Osmaniye': ['Merkez', 'Kadirli', 'Düziçi', 'Bahçe', 'Toprakkale', 'Hasanbeyli', 'Sumbas'],
  'Rize': ['Merkez', 'Çayeli', 'Ardeşen', 'Pazar', 'Fındıklı', 'Güneysu', 'İkizdere', 'Kalkandere', 'Derepazarı', 'İyidere', 'Hemşin', 'Çamlıhemşin'],
  'Sakarya': ['Adapazarı', 'Serdivan', 'Erenler', 'Arifiye', 'Hendek', 'Akyazı', 'Geyve', 'Sapanca', 'Karasu', 'Kocaali', 'Kaynarca', 'Ferizli', 'Söğütlü', 'Pamukova', 'Taraklı', 'Karapürçek'],
  'Samsun': ['İlkadım', 'Atakum', 'Canik', 'Tekkeköy', 'Bafra', 'Çarşamba', 'Terme', 'Vezirköprü', 'Havza', 'Kavak', 'Alaçam', 'Ladik', 'Salıpazarı', 'Asarcık', 'Ayvacık', 'Yakakent', '19 Mayıs'],
  'Siirt': ['Merkez', 'Kurtalan', 'Pervari', 'Şirvan', 'Baykan', 'Eruh', 'Tillo'],
  'Sinop': ['Merkez', 'Boyabat', 'Gerze', 'Ayancık', 'Türkeli', 'Durağan', 'Erfelek', 'Dikmen', 'Saraydüzü'],
  'Sivas': ['Merkez', 'Şarkışla', 'Yıldızeli', 'Gemerek', 'Suşehri', 'Zara', 'Kangal', 'Divriği', 'Gürün', 'Hafik', 'Koyulhisar', 'İmranlı', 'Akıncılar', 'Altınyayla', 'Doğanşar', 'Gölova', 'Ulaş'],
  'Şanlıurfa': ['Eyyübiye', 'Haliliye', 'Karaköprü', 'Siverek', 'Viranşehir', 'Akçakale', 'Birecik', 'Suruç', 'Bozova', 'Ceylanpınar', 'Harran', 'Hilvan', 'Halfeti'],
  'Şırnak': ['Merkez', 'Cizre', 'Silopi', 'İdil', 'Uludere', 'Beytüşşebap', 'Güçlükonak'],
  'Tekirdağ': ['Süleymanpaşa', 'Çorlu', 'Çerkezköy', 'Ergene', 'Kapaklı', 'Saray', 'Muratlı', 'Malkara', 'Hayrabolu', 'Şarköy', 'Marmaraereğlisi'],
  'Tokat': ['Merkez', 'Turhal', 'Erbaa', 'Niksar', 'Zile', 'Almus', 'Reşadiye', 'Artova', 'Pazar', 'Sulusaray', 'Başçiftlik', 'Yeşilyurt'],
  'Trabzon': ['Ortahisar', 'Akçaabat', 'Araklı', 'Of', 'Yomra', 'Arsin', 'Beşikdüzü', 'Çarşıbaşı', 'Düzköy', 'Hayrat', 'Köprübaşı', 'Maçka', 'Sürmene', 'Şalpazarı', 'Tonya', 'Vakfıkebir', 'Dernekpazarı', 'Çaykara'],
  'Tunceli': ['Merkez', 'Pertek', 'Çemişgezek', 'Hozat', 'Ovacık', 'Mazgirt', 'Nazımiye', 'Pülümür'],
  'Uşak': ['Merkez', 'Eşme', 'Banaz', 'Sivaslı', 'Ulubey', 'Karahallı'],
  'Van': ['İpekyolu', 'Tuşba', 'Edremit', 'Erciş', 'Özalp', 'Çaldıran', 'Muradiye', 'Başkale', 'Gürpınar', 'Gevaş', 'Çatak', 'Bahçesaray', 'Saray'],
  'Yalova': ['Merkez', 'Çiftlikköy', 'Çınarcık', 'Armutlu', 'Altınova', 'Termal'],
  'Yozgat': ['Merkez', 'Sorgun', 'Yerköy', 'Akdağmadeni', 'Boğazlıyan', 'Çekerek', 'Sarıkaya', 'Şefaatli', 'Aydıncık', 'Çayıralan', 'Çandır', 'Kadışehri', 'Saraykent', 'Yenifakılı'],
  'Zonguldak': ['Merkez', 'Ereğli', 'Karadeniz Ereğli', 'Çaycuma', 'Devrek', 'Alaplı', 'Gökçebey', 'Kilimli', 'Kozlu']
};

export function getCityOptions() {
  return TURKEY_CITIES.map(city => ({ value: city, label: city }));
}

export function getDistrictOptions(city: string): { value: string; label: string }[] {
  const districts = TURKEY_DISTRICTS[city] || [];
  return districts.map(district => ({ value: district, label: district }));
}
